/*
 * PaypalServerSdkLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.paypal.sdk.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for CreateSubscriptionInput type.
 */
public class CreateSubscriptionInput {
    private String contentType;
    private String prefer;
    private String paypalRequestId;
    private String paypalClientMetadataId;
    private CreateSubscriptionRequest body;

    /**
     * Default constructor.
     */
    public CreateSubscriptionInput() {
        contentType = "application/json";
        prefer = "return=minimal";
    }

    /**
     * Initialization constructor.
     * @param  contentType  String value for contentType.
     * @param  prefer  String value for prefer.
     * @param  paypalRequestId  String value for paypalRequestId.
     * @param  paypalClientMetadataId  String value for paypalClientMetadataId.
     * @param  body  CreateSubscriptionRequest value for body.
     */
    public CreateSubscriptionInput(
            String contentType,
            String prefer,
            String paypalRequestId,
            String paypalClientMetadataId,
            CreateSubscriptionRequest body) {
        this.contentType = contentType;
        this.prefer = prefer;
        this.paypalRequestId = paypalRequestId;
        this.paypalClientMetadataId = paypalClientMetadataId;
        this.body = body;
    }

    /**
     * Getter for ContentType.
     * @return Returns the String
     */
    @JsonGetter("Content-Type")
    public String getContentType() {
        return contentType;
    }

    /**
     * Setter for ContentType.
     * @param contentType Value for String
     */
    @JsonSetter("Content-Type")
    private void setContentType(String contentType) {
        this.contentType = contentType;
    }

    /**
     * Getter for Prefer.
     * The preferred server response upon successful completion of the request. Value is:
     * return=minimal. The server returns a minimal response to optimize communication between the
     * API caller and the server. A minimal response includes the id, status and HATEOAS links.
     * return=representation. The server returns a complete resource representation, including the
     * current state of the resource.
     * @return Returns the String
     */
    @JsonGetter("Prefer")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getPrefer() {
        return prefer;
    }

    /**
     * Setter for Prefer.
     * The preferred server response upon successful completion of the request. Value is:
     * return=minimal. The server returns a minimal response to optimize communication between the
     * API caller and the server. A minimal response includes the id, status and HATEOAS links.
     * return=representation. The server returns a complete resource representation, including the
     * current state of the resource.
     * @param prefer Value for String
     */
    @JsonSetter("Prefer")
    public void setPrefer(String prefer) {
        this.prefer = prefer;
    }

    /**
     * Getter for PaypalRequestId.
     * The server stores keys for 72 hours.
     * @return Returns the String
     */
    @JsonGetter("PayPal-Request-Id")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getPaypalRequestId() {
        return paypalRequestId;
    }

    /**
     * Setter for PaypalRequestId.
     * The server stores keys for 72 hours.
     * @param paypalRequestId Value for String
     */
    @JsonSetter("PayPal-Request-Id")
    public void setPaypalRequestId(String paypalRequestId) {
        this.paypalRequestId = paypalRequestId;
    }

    /**
     * Getter for PaypalClientMetadataId.
     * The PayPal Client Metadata Id(CMID) is used to provide device-specific information to
     * PayPal's risk engine. This is crucial for transactions that require device-specific risk
     * assessments. Merchants typically use the Paypal SDK that automatically submits the CMID or
     * they use tools like Fraudnet JS for web or Magnes JS for mobile to generate the CMID on the
     * frontend and then pass it to the API as part of the request headers.
     * @return Returns the String
     */
    @JsonGetter("PayPal-Client-Metadata-Id")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getPaypalClientMetadataId() {
        return paypalClientMetadataId;
    }

    /**
     * Setter for PaypalClientMetadataId.
     * The PayPal Client Metadata Id(CMID) is used to provide device-specific information to
     * PayPal's risk engine. This is crucial for transactions that require device-specific risk
     * assessments. Merchants typically use the Paypal SDK that automatically submits the CMID or
     * they use tools like Fraudnet JS for web or Magnes JS for mobile to generate the CMID on the
     * frontend and then pass it to the API as part of the request headers.
     * @param paypalClientMetadataId Value for String
     */
    @JsonSetter("PayPal-Client-Metadata-Id")
    public void setPaypalClientMetadataId(String paypalClientMetadataId) {
        this.paypalClientMetadataId = paypalClientMetadataId;
    }

    /**
     * Getter for Body.
     * @return Returns the CreateSubscriptionRequest
     */
    @JsonGetter("body")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public CreateSubscriptionRequest getBody() {
        return body;
    }

    /**
     * Setter for Body.
     * @param body Value for CreateSubscriptionRequest
     */
    @JsonSetter("body")
    public void setBody(CreateSubscriptionRequest body) {
        this.body = body;
    }

    /**
     * Converts this CreateSubscriptionInput into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "CreateSubscriptionInput [" + "contentType=" + contentType + ", prefer=" + prefer
                + ", paypalRequestId=" + paypalRequestId + ", paypalClientMetadataId="
                + paypalClientMetadataId + ", body=" + body + "]";
    }

    /**
     * Builds a new {@link CreateSubscriptionInput.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link CreateSubscriptionInput.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(contentType)
                .prefer(getPrefer())
                .paypalRequestId(getPaypalRequestId())
                .paypalClientMetadataId(getPaypalClientMetadataId())
                .body(getBody());
        return builder;
    }

    /**
     * Class to build instances of {@link CreateSubscriptionInput}.
     */
    public static class Builder {
        private String contentType = "application/json";
        private String prefer = "return=minimal";
        private String paypalRequestId;
        private String paypalClientMetadataId;
        private CreateSubscriptionRequest body;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  contentType  String value for contentType.
         */
        public Builder(String contentType) {
            this.contentType = contentType;
        }

        /**
         * Setter for contentType.
         * @param  contentType  String value for contentType.
         * @return Builder
         */
        public Builder contentType(String contentType) {
            this.contentType = contentType;
            return this;
        }

        /**
         * Setter for prefer.
         * @param  prefer  String value for prefer.
         * @return Builder
         */
        public Builder prefer(String prefer) {
            this.prefer = prefer;
            return this;
        }

        /**
         * Setter for paypalRequestId.
         * @param  paypalRequestId  String value for paypalRequestId.
         * @return Builder
         */
        public Builder paypalRequestId(String paypalRequestId) {
            this.paypalRequestId = paypalRequestId;
            return this;
        }

        /**
         * Setter for paypalClientMetadataId.
         * @param  paypalClientMetadataId  String value for paypalClientMetadataId.
         * @return Builder
         */
        public Builder paypalClientMetadataId(String paypalClientMetadataId) {
            this.paypalClientMetadataId = paypalClientMetadataId;
            return this;
        }

        /**
         * Setter for body.
         * @param  body  CreateSubscriptionRequest value for body.
         * @return Builder
         */
        public Builder body(CreateSubscriptionRequest body) {
            this.body = body;
            return this;
        }

        /**
         * Builds a new {@link CreateSubscriptionInput} object using the set fields.
         * @return {@link CreateSubscriptionInput}
         */
        public CreateSubscriptionInput build() {
            return new CreateSubscriptionInput(contentType, prefer, paypalRequestId,
                    paypalClientMetadataId, body);
        }
    }
}
