/*
 * PaypalServerSdkLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.paypal.sdk.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for CreateSubscriptionRequest type.
 */
public class CreateSubscriptionRequest {
    private String planId;
    private String startTime;
    private String quantity;
    private Money shippingAmount;
    private SubscriberRequest subscriber;
    private Boolean autoRenewal;
    private SubscriptionApplicationContext applicationContext;
    private String customId;
    private PlanOverride plan;

    /**
     * Default constructor.
     */
    public CreateSubscriptionRequest() {
        autoRenewal = false;
    }

    /**
     * Initialization constructor.
     * @param  planId  String value for planId.
     * @param  startTime  String value for startTime.
     * @param  quantity  String value for quantity.
     * @param  shippingAmount  Money value for shippingAmount.
     * @param  subscriber  SubscriberRequest value for subscriber.
     * @param  autoRenewal  Boolean value for autoRenewal.
     * @param  applicationContext  SubscriptionApplicationContext value for applicationContext.
     * @param  customId  String value for customId.
     * @param  plan  PlanOverride value for plan.
     */
    public CreateSubscriptionRequest(
            String planId,
            String startTime,
            String quantity,
            Money shippingAmount,
            SubscriberRequest subscriber,
            Boolean autoRenewal,
            SubscriptionApplicationContext applicationContext,
            String customId,
            PlanOverride plan) {
        this.planId = planId;
        this.startTime = startTime;
        this.quantity = quantity;
        this.shippingAmount = shippingAmount;
        this.subscriber = subscriber;
        this.autoRenewal = autoRenewal;
        this.applicationContext = applicationContext;
        this.customId = customId;
        this.plan = plan;
    }

    /**
     * Getter for PlanId.
     * The ID of the plan.
     * @return Returns the String
     */
    @JsonGetter("plan_id")
    public String getPlanId() {
        return planId;
    }

    /**
     * Setter for PlanId.
     * The ID of the plan.
     * @param planId Value for String
     */
    @JsonSetter("plan_id")
    public void setPlanId(String planId) {
        this.planId = planId;
    }

    /**
     * Getter for StartTime.
     * The date and time, in [Internet date and time
     * format](https://tools.ietf.org/html/rfc3339#section-5.6). Seconds are required while
     * fractional seconds are optional. Note: The regular expression provides guidance but does not
     * reject all invalid dates.
     * @return Returns the String
     */
    @JsonGetter("start_time")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getStartTime() {
        return startTime;
    }

    /**
     * Setter for StartTime.
     * The date and time, in [Internet date and time
     * format](https://tools.ietf.org/html/rfc3339#section-5.6). Seconds are required while
     * fractional seconds are optional. Note: The regular expression provides guidance but does not
     * reject all invalid dates.
     * @param startTime Value for String
     */
    @JsonSetter("start_time")
    public void setStartTime(String startTime) {
        this.startTime = startTime;
    }

    /**
     * Getter for Quantity.
     * The quantity of the product in the subscription.
     * @return Returns the String
     */
    @JsonGetter("quantity")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getQuantity() {
        return quantity;
    }

    /**
     * Setter for Quantity.
     * The quantity of the product in the subscription.
     * @param quantity Value for String
     */
    @JsonSetter("quantity")
    public void setQuantity(String quantity) {
        this.quantity = quantity;
    }

    /**
     * Getter for ShippingAmount.
     * The currency and amount for a financial transaction, such as a balance or payment due.
     * @return Returns the Money
     */
    @JsonGetter("shipping_amount")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Money getShippingAmount() {
        return shippingAmount;
    }

    /**
     * Setter for ShippingAmount.
     * The currency and amount for a financial transaction, such as a balance or payment due.
     * @param shippingAmount Value for Money
     */
    @JsonSetter("shipping_amount")
    public void setShippingAmount(Money shippingAmount) {
        this.shippingAmount = shippingAmount;
    }

    /**
     * Getter for Subscriber.
     * The subscriber request information .
     * @return Returns the SubscriberRequest
     */
    @JsonGetter("subscriber")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public SubscriberRequest getSubscriber() {
        return subscriber;
    }

    /**
     * Setter for Subscriber.
     * The subscriber request information .
     * @param subscriber Value for SubscriberRequest
     */
    @JsonSetter("subscriber")
    public void setSubscriber(SubscriberRequest subscriber) {
        this.subscriber = subscriber;
    }

    /**
     * Getter for AutoRenewal.
     * DEPRECATED. Indicates whether the subscription auto-renews after the billing cycles complete.
     * @return Returns the Boolean
     */
    @JsonGetter("auto_renewal")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Boolean getAutoRenewal() {
        return autoRenewal;
    }

    /**
     * Setter for AutoRenewal.
     * DEPRECATED. Indicates whether the subscription auto-renews after the billing cycles complete.
     * @param autoRenewal Value for Boolean
     */
    @JsonSetter("auto_renewal")
    public void setAutoRenewal(Boolean autoRenewal) {
        this.autoRenewal = autoRenewal;
    }

    /**
     * Getter for ApplicationContext.
     * DEPRECATED. The application context, which customizes the payer experience during the
     * subscription approval process with PayPal.
     * @return Returns the SubscriptionApplicationContext
     */
    @JsonGetter("application_context")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public SubscriptionApplicationContext getApplicationContext() {
        return applicationContext;
    }

    /**
     * Setter for ApplicationContext.
     * DEPRECATED. The application context, which customizes the payer experience during the
     * subscription approval process with PayPal.
     * @param applicationContext Value for SubscriptionApplicationContext
     */
    @JsonSetter("application_context")
    public void setApplicationContext(SubscriptionApplicationContext applicationContext) {
        this.applicationContext = applicationContext;
    }

    /**
     * Getter for CustomId.
     * The custom id for the subscription. Can be invoice id.
     * @return Returns the String
     */
    @JsonGetter("custom_id")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getCustomId() {
        return customId;
    }

    /**
     * Setter for CustomId.
     * The custom id for the subscription. Can be invoice id.
     * @param customId Value for String
     */
    @JsonSetter("custom_id")
    public void setCustomId(String customId) {
        this.customId = customId;
    }

    /**
     * Getter for Plan.
     * An inline plan object to customise the subscription. You can override plan level default
     * attributes by providing customised values for the subscription in this object.
     * @return Returns the PlanOverride
     */
    @JsonGetter("plan")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public PlanOverride getPlan() {
        return plan;
    }

    /**
     * Setter for Plan.
     * An inline plan object to customise the subscription. You can override plan level default
     * attributes by providing customised values for the subscription in this object.
     * @param plan Value for PlanOverride
     */
    @JsonSetter("plan")
    public void setPlan(PlanOverride plan) {
        this.plan = plan;
    }

    /**
     * Converts this CreateSubscriptionRequest into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "CreateSubscriptionRequest [" + "planId=" + planId + ", startTime=" + startTime
                + ", quantity=" + quantity + ", shippingAmount=" + shippingAmount + ", subscriber="
                + subscriber + ", autoRenewal=" + autoRenewal + ", applicationContext="
                + applicationContext + ", customId=" + customId + ", plan=" + plan + "]";
    }

    /**
     * Builds a new {@link CreateSubscriptionRequest.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link CreateSubscriptionRequest.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(planId)
                .startTime(getStartTime())
                .quantity(getQuantity())
                .shippingAmount(getShippingAmount())
                .subscriber(getSubscriber())
                .autoRenewal(getAutoRenewal())
                .applicationContext(getApplicationContext())
                .customId(getCustomId())
                .plan(getPlan());
        return builder;
    }

    /**
     * Class to build instances of {@link CreateSubscriptionRequest}.
     */
    public static class Builder {
        private String planId;
        private String startTime;
        private String quantity;
        private Money shippingAmount;
        private SubscriberRequest subscriber;
        private Boolean autoRenewal = false;
        private SubscriptionApplicationContext applicationContext;
        private String customId;
        private PlanOverride plan;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  planId  String value for planId.
         */
        public Builder(String planId) {
            this.planId = planId;
        }

        /**
         * Setter for planId.
         * @param  planId  String value for planId.
         * @return Builder
         */
        public Builder planId(String planId) {
            this.planId = planId;
            return this;
        }

        /**
         * Setter for startTime.
         * @param  startTime  String value for startTime.
         * @return Builder
         */
        public Builder startTime(String startTime) {
            this.startTime = startTime;
            return this;
        }

        /**
         * Setter for quantity.
         * @param  quantity  String value for quantity.
         * @return Builder
         */
        public Builder quantity(String quantity) {
            this.quantity = quantity;
            return this;
        }

        /**
         * Setter for shippingAmount.
         * @param  shippingAmount  Money value for shippingAmount.
         * @return Builder
         */
        public Builder shippingAmount(Money shippingAmount) {
            this.shippingAmount = shippingAmount;
            return this;
        }

        /**
         * Setter for subscriber.
         * @param  subscriber  SubscriberRequest value for subscriber.
         * @return Builder
         */
        public Builder subscriber(SubscriberRequest subscriber) {
            this.subscriber = subscriber;
            return this;
        }

        /**
         * Setter for autoRenewal.
         * @param  autoRenewal  Boolean value for autoRenewal.
         * @return Builder
         */
        public Builder autoRenewal(Boolean autoRenewal) {
            this.autoRenewal = autoRenewal;
            return this;
        }

        /**
         * Setter for applicationContext.
         * @param  applicationContext  SubscriptionApplicationContext value for applicationContext.
         * @return Builder
         */
        public Builder applicationContext(SubscriptionApplicationContext applicationContext) {
            this.applicationContext = applicationContext;
            return this;
        }

        /**
         * Setter for customId.
         * @param  customId  String value for customId.
         * @return Builder
         */
        public Builder customId(String customId) {
            this.customId = customId;
            return this;
        }

        /**
         * Setter for plan.
         * @param  plan  PlanOverride value for plan.
         * @return Builder
         */
        public Builder plan(PlanOverride plan) {
            this.plan = plan;
            return this;
        }

        /**
         * Builds a new {@link CreateSubscriptionRequest} object using the set fields.
         * @return {@link CreateSubscriptionRequest}
         */
        public CreateSubscriptionRequest build() {
            return new CreateSubscriptionRequest(planId, startTime, quantity, shippingAmount,
                    subscriber, autoRenewal, applicationContext, customId, plan);
        }
    }
}
