/*
 * PaypalServerSdkLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.paypal.sdk.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for CycleFrequency type.
 */
public class CycleFrequency {
    private FrequencyIntervalUnit intervalUnit;
    private Integer intervalCount;

    /**
     * Default constructor.
     */
    public CycleFrequency() {
        intervalCount = 1;
    }

    /**
     * Initialization constructor.
     * @param  intervalUnit  FrequencyIntervalUnit value for intervalUnit.
     * @param  intervalCount  Integer value for intervalCount.
     */
    public CycleFrequency(
            FrequencyIntervalUnit intervalUnit,
            Integer intervalCount) {
        this.intervalUnit = intervalUnit;
        this.intervalCount = intervalCount;
    }

    /**
     * Getter for IntervalUnit.
     * The interval unit at which the the usage limits will be reset.
     * @return Returns the FrequencyIntervalUnit
     */
    @JsonGetter("interval_unit")
    public FrequencyIntervalUnit getIntervalUnit() {
        return intervalUnit;
    }

    /**
     * Setter for IntervalUnit.
     * The interval unit at which the the usage limits will be reset.
     * @param intervalUnit Value for FrequencyIntervalUnit
     */
    @JsonSetter("interval_unit")
    public void setIntervalUnit(FrequencyIntervalUnit intervalUnit) {
        this.intervalUnit = intervalUnit;
    }

    /**
     * Getter for IntervalCount.
     * The interval count at which the terms will be reset, this is ignored if the unit is LIFETIME.
     * @return Returns the Integer
     */
    @JsonGetter("interval_count")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getIntervalCount() {
        return intervalCount;
    }

    /**
     * Setter for IntervalCount.
     * The interval count at which the terms will be reset, this is ignored if the unit is LIFETIME.
     * @param intervalCount Value for Integer
     */
    @JsonSetter("interval_count")
    public void setIntervalCount(Integer intervalCount) {
        this.intervalCount = intervalCount;
    }

    /**
     * Converts this CycleFrequency into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "CycleFrequency [" + "intervalUnit=" + intervalUnit + ", intervalCount="
                + intervalCount + "]";
    }

    /**
     * Builds a new {@link CycleFrequency.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link CycleFrequency.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(intervalUnit)
                .intervalCount(getIntervalCount());
        return builder;
    }

    /**
     * Class to build instances of {@link CycleFrequency}.
     */
    public static class Builder {
        private FrequencyIntervalUnit intervalUnit;
        private Integer intervalCount = 1;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  intervalUnit  FrequencyIntervalUnit value for intervalUnit.
         */
        public Builder(FrequencyIntervalUnit intervalUnit) {
            this.intervalUnit = intervalUnit;
        }

        /**
         * Setter for intervalUnit.
         * @param  intervalUnit  FrequencyIntervalUnit value for intervalUnit.
         * @return Builder
         */
        public Builder intervalUnit(FrequencyIntervalUnit intervalUnit) {
            this.intervalUnit = intervalUnit;
            return this;
        }

        /**
         * Setter for intervalCount.
         * @param  intervalCount  Integer value for intervalCount.
         * @return Builder
         */
        public Builder intervalCount(Integer intervalCount) {
            this.intervalCount = intervalCount;
            return this;
        }

        /**
         * Builds a new {@link CycleFrequency} object using the set fields.
         * @return {@link CycleFrequency}
         */
        public CycleFrequency build() {
            return new CycleFrequency(intervalUnit, intervalCount);
        }
    }
}
