/*
 * PaypalServerSdkLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.paypal.sdk.models;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;


/**
 * IntervalUnit to be used.
 */
public enum IntervalUnit {
    /**
     * A daily billing cycle.
     */
    DAY,

    /**
     * A weekly billing cycle.
     */
    WEEK,

    /**
     * A monthly billing cycle.
     */
    MONTH,

    /**
     * A yearly billing cycle.
     */
    YEAR,

    /**
     * Unknown values will be mapped by this enum member
     */
    _UNKNOWN;


    private static TreeMap<String, IntervalUnit> valueMap = new TreeMap<>();
    private String value;

    static {
        DAY.value = "DAY";
        WEEK.value = "WEEK";
        MONTH.value = "MONTH";
        YEAR.value = "YEAR";
        _UNKNOWN.value = null;

        valueMap.put("DAY", DAY);
        valueMap.put("WEEK", WEEK);
        valueMap.put("MONTH", MONTH);
        valueMap.put("YEAR", YEAR);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     * @throws IOException when provided value is not mapped to any enum member.
     */
    @JsonCreator
    public static IntervalUnit constructFromString(String toConvert) throws IOException {
        IntervalUnit enumValue = fromString(toConvert);
        if (enumValue == null) {
            throw new IOException("Unable to create enum instance with value: " + toConvert);
        }
        return enumValue;
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    public static IntervalUnit fromString(String toConvert) {
        if (!valueMap.containsKey(toConvert)) {
            return _UNKNOWN;
        }
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        if (value == null) {
            return null;
        }
        return value.toString();
    }

    /**
     * Convert list of IntervalUnit values to list of string values.
     * @param toConvert The list of IntervalUnit values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<IntervalUnit> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (IntervalUnit enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 