/*
 * PaypalServerSdkLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.paypal.sdk.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;

/**
 * This is a model class for ListSubscriptionsInput type.
 */
public class ListSubscriptionsInput {
    private String planIds;
    private String statuses;
    private String createdAfter;
    private String createdBefore;
    private String statusUpdatedBefore;
    private String statusUpdatedAfter;
    private String filter;
    private Integer pageSize;
    private Integer page;
    private List<String> customerIds;

    /**
     * Default constructor.
     */
    public ListSubscriptionsInput() {
        pageSize = 10;
        page = 1;
    }

    /**
     * Initialization constructor.
     * @param  planIds  String value for planIds.
     * @param  statuses  String value for statuses.
     * @param  createdAfter  String value for createdAfter.
     * @param  createdBefore  String value for createdBefore.
     * @param  statusUpdatedBefore  String value for statusUpdatedBefore.
     * @param  statusUpdatedAfter  String value for statusUpdatedAfter.
     * @param  filter  String value for filter.
     * @param  pageSize  Integer value for pageSize.
     * @param  page  Integer value for page.
     * @param  customerIds  List of String value for customerIds.
     */
    public ListSubscriptionsInput(
            String planIds,
            String statuses,
            String createdAfter,
            String createdBefore,
            String statusUpdatedBefore,
            String statusUpdatedAfter,
            String filter,
            Integer pageSize,
            Integer page,
            List<String> customerIds) {
        this.planIds = planIds;
        this.statuses = statuses;
        this.createdAfter = createdAfter;
        this.createdBefore = createdBefore;
        this.statusUpdatedBefore = statusUpdatedBefore;
        this.statusUpdatedAfter = statusUpdatedAfter;
        this.filter = filter;
        this.pageSize = pageSize;
        this.page = page;
        this.customerIds = customerIds;
    }

    /**
     * Getter for PlanIds.
     * Filters the response by list of plan IDs. Filter supports upto 70 plan IDs. URLs should not
     * exceed a length of 2000 characters.
     * @return Returns the String
     */
    @JsonGetter("plan_ids")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getPlanIds() {
        return planIds;
    }

    /**
     * Setter for PlanIds.
     * Filters the response by list of plan IDs. Filter supports upto 70 plan IDs. URLs should not
     * exceed a length of 2000 characters.
     * @param planIds Value for String
     */
    @JsonSetter("plan_ids")
    public void setPlanIds(String planIds) {
        this.planIds = planIds;
    }

    /**
     * Getter for Statuses.
     * Filters the response by list of subscription statuses.
     * @return Returns the String
     */
    @JsonGetter("statuses")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getStatuses() {
        return statuses;
    }

    /**
     * Setter for Statuses.
     * Filters the response by list of subscription statuses.
     * @param statuses Value for String
     */
    @JsonSetter("statuses")
    public void setStatuses(String statuses) {
        this.statuses = statuses;
    }

    /**
     * Getter for CreatedAfter.
     * Filters the response by subscription creation start time for a range of subscriptions.
     * @return Returns the String
     */
    @JsonGetter("created_after")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getCreatedAfter() {
        return createdAfter;
    }

    /**
     * Setter for CreatedAfter.
     * Filters the response by subscription creation start time for a range of subscriptions.
     * @param createdAfter Value for String
     */
    @JsonSetter("created_after")
    public void setCreatedAfter(String createdAfter) {
        this.createdAfter = createdAfter;
    }

    /**
     * Getter for CreatedBefore.
     * Filters the response by subscription creation end time for a range of subscriptions.
     * @return Returns the String
     */
    @JsonGetter("created_before")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getCreatedBefore() {
        return createdBefore;
    }

    /**
     * Setter for CreatedBefore.
     * Filters the response by subscription creation end time for a range of subscriptions.
     * @param createdBefore Value for String
     */
    @JsonSetter("created_before")
    public void setCreatedBefore(String createdBefore) {
        this.createdBefore = createdBefore;
    }

    /**
     * Getter for StatusUpdatedBefore.
     * Filters the response by status update start time for a range of subscriptions.
     * @return Returns the String
     */
    @JsonGetter("status_updated_before")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getStatusUpdatedBefore() {
        return statusUpdatedBefore;
    }

    /**
     * Setter for StatusUpdatedBefore.
     * Filters the response by status update start time for a range of subscriptions.
     * @param statusUpdatedBefore Value for String
     */
    @JsonSetter("status_updated_before")
    public void setStatusUpdatedBefore(String statusUpdatedBefore) {
        this.statusUpdatedBefore = statusUpdatedBefore;
    }

    /**
     * Getter for StatusUpdatedAfter.
     * Filters the response by status update end time for a range of subscriptions.
     * @return Returns the String
     */
    @JsonGetter("status_updated_after")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getStatusUpdatedAfter() {
        return statusUpdatedAfter;
    }

    /**
     * Setter for StatusUpdatedAfter.
     * Filters the response by status update end time for a range of subscriptions.
     * @param statusUpdatedAfter Value for String
     */
    @JsonSetter("status_updated_after")
    public void setStatusUpdatedAfter(String statusUpdatedAfter) {
        this.statusUpdatedAfter = statusUpdatedAfter;
    }

    /**
     * Getter for Filter.
     * Filter the response using complex expressions that could use comparison operators like ge,
     * gt, le, lt and logical operators such as 'and' and 'or'.
     * @return Returns the String
     */
    @JsonGetter("filter")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getFilter() {
        return filter;
    }

    /**
     * Setter for Filter.
     * Filter the response using complex expressions that could use comparison operators like ge,
     * gt, le, lt and logical operators such as 'and' and 'or'.
     * @param filter Value for String
     */
    @JsonSetter("filter")
    public void setFilter(String filter) {
        this.filter = filter;
    }

    /**
     * Getter for PageSize.
     * The number of items to return in the response.
     * @return Returns the Integer
     */
    @JsonGetter("page_size")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getPageSize() {
        return pageSize;
    }

    /**
     * Setter for PageSize.
     * The number of items to return in the response.
     * @param pageSize Value for Integer
     */
    @JsonSetter("page_size")
    public void setPageSize(Integer pageSize) {
        this.pageSize = pageSize;
    }

    /**
     * Getter for Page.
     * A non-zero integer which is the start index of the entire list of items to return in the
     * response. The combination of `page=1` and `page_size=20` returns the first 20 items. The
     * combination of `page=2` and `page_size=20` returns the next 20 items.
     * @return Returns the Integer
     */
    @JsonGetter("page")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getPage() {
        return page;
    }

    /**
     * Setter for Page.
     * A non-zero integer which is the start index of the entire list of items to return in the
     * response. The combination of `page=1` and `page_size=20` returns the first 20 items. The
     * combination of `page=2` and `page_size=20` returns the next 20 items.
     * @param page Value for Integer
     */
    @JsonSetter("page")
    public void setPage(Integer page) {
        this.page = page;
    }

    /**
     * Getter for CustomerIds.
     * Filters the response by comma separated vault customer IDs (FSS subscriptions only).
     * @return Returns the List of String
     */
    @JsonGetter("customer_ids")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<String> getCustomerIds() {
        return customerIds;
    }

    /**
     * Setter for CustomerIds.
     * Filters the response by comma separated vault customer IDs (FSS subscriptions only).
     * @param customerIds Value for List of String
     */
    @JsonSetter("customer_ids")
    public void setCustomerIds(List<String> customerIds) {
        this.customerIds = customerIds;
    }

    /**
     * Converts this ListSubscriptionsInput into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ListSubscriptionsInput [" + "planIds=" + planIds + ", statuses=" + statuses
                + ", createdAfter=" + createdAfter + ", createdBefore=" + createdBefore
                + ", statusUpdatedBefore=" + statusUpdatedBefore + ", statusUpdatedAfter="
                + statusUpdatedAfter + ", filter=" + filter + ", pageSize=" + pageSize + ", page="
                + page + ", customerIds=" + customerIds + "]";
    }

    /**
     * Builds a new {@link ListSubscriptionsInput.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link ListSubscriptionsInput.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .planIds(getPlanIds())
                .statuses(getStatuses())
                .createdAfter(getCreatedAfter())
                .createdBefore(getCreatedBefore())
                .statusUpdatedBefore(getStatusUpdatedBefore())
                .statusUpdatedAfter(getStatusUpdatedAfter())
                .filter(getFilter())
                .pageSize(getPageSize())
                .page(getPage())
                .customerIds(getCustomerIds());
        return builder;
    }

    /**
     * Class to build instances of {@link ListSubscriptionsInput}.
     */
    public static class Builder {
        private String planIds;
        private String statuses;
        private String createdAfter;
        private String createdBefore;
        private String statusUpdatedBefore;
        private String statusUpdatedAfter;
        private String filter;
        private Integer pageSize = 10;
        private Integer page = 1;
        private List<String> customerIds;



        /**
         * Setter for planIds.
         * @param  planIds  String value for planIds.
         * @return Builder
         */
        public Builder planIds(String planIds) {
            this.planIds = planIds;
            return this;
        }

        /**
         * Setter for statuses.
         * @param  statuses  String value for statuses.
         * @return Builder
         */
        public Builder statuses(String statuses) {
            this.statuses = statuses;
            return this;
        }

        /**
         * Setter for createdAfter.
         * @param  createdAfter  String value for createdAfter.
         * @return Builder
         */
        public Builder createdAfter(String createdAfter) {
            this.createdAfter = createdAfter;
            return this;
        }

        /**
         * Setter for createdBefore.
         * @param  createdBefore  String value for createdBefore.
         * @return Builder
         */
        public Builder createdBefore(String createdBefore) {
            this.createdBefore = createdBefore;
            return this;
        }

        /**
         * Setter for statusUpdatedBefore.
         * @param  statusUpdatedBefore  String value for statusUpdatedBefore.
         * @return Builder
         */
        public Builder statusUpdatedBefore(String statusUpdatedBefore) {
            this.statusUpdatedBefore = statusUpdatedBefore;
            return this;
        }

        /**
         * Setter for statusUpdatedAfter.
         * @param  statusUpdatedAfter  String value for statusUpdatedAfter.
         * @return Builder
         */
        public Builder statusUpdatedAfter(String statusUpdatedAfter) {
            this.statusUpdatedAfter = statusUpdatedAfter;
            return this;
        }

        /**
         * Setter for filter.
         * @param  filter  String value for filter.
         * @return Builder
         */
        public Builder filter(String filter) {
            this.filter = filter;
            return this;
        }

        /**
         * Setter for pageSize.
         * @param  pageSize  Integer value for pageSize.
         * @return Builder
         */
        public Builder pageSize(Integer pageSize) {
            this.pageSize = pageSize;
            return this;
        }

        /**
         * Setter for page.
         * @param  page  Integer value for page.
         * @return Builder
         */
        public Builder page(Integer page) {
            this.page = page;
            return this;
        }

        /**
         * Setter for customerIds.
         * @param  customerIds  List of String value for customerIds.
         * @return Builder
         */
        public Builder customerIds(List<String> customerIds) {
            this.customerIds = customerIds;
            return this;
        }

        /**
         * Builds a new {@link ListSubscriptionsInput} object using the set fields.
         * @return {@link ListSubscriptionsInput}
         */
        public ListSubscriptionsInput build() {
            return new ListSubscriptionsInput(planIds, statuses, createdAfter, createdBefore,
                    statusUpdatedBefore, statusUpdatedAfter, filter, pageSize, page, customerIds);
        }
    }
}
