/*
 * PaypalServerSdkLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.paypal.sdk.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for ListSubscriptionTransactionsInput type.
 */
public class ListSubscriptionTransactionsInput {
    private String id;
    private String startTime;
    private String endTime;

    /**
     * Default constructor.
     */
    public ListSubscriptionTransactionsInput() {
    }

    /**
     * Initialization constructor.
     * @param  id  String value for id.
     * @param  startTime  String value for startTime.
     * @param  endTime  String value for endTime.
     */
    public ListSubscriptionTransactionsInput(
            String id,
            String startTime,
            String endTime) {
        this.id = id;
        this.startTime = startTime;
        this.endTime = endTime;
    }

    /**
     * Getter for Id.
     * The ID of the subscription.
     * @return Returns the String
     */
    @JsonGetter("id")
    public String getId() {
        return id;
    }

    /**
     * Setter for Id.
     * The ID of the subscription.
     * @param id Value for String
     */
    @JsonSetter("id")
    public void setId(String id) {
        this.id = id;
    }

    /**
     * Getter for StartTime.
     * The start time of the range of transactions to list.
     * @return Returns the String
     */
    @JsonGetter("start_time")
    public String getStartTime() {
        return startTime;
    }

    /**
     * Setter for StartTime.
     * The start time of the range of transactions to list.
     * @param startTime Value for String
     */
    @JsonSetter("start_time")
    public void setStartTime(String startTime) {
        this.startTime = startTime;
    }

    /**
     * Getter for EndTime.
     * The end time of the range of transactions to list.
     * @return Returns the String
     */
    @JsonGetter("end_time")
    public String getEndTime() {
        return endTime;
    }

    /**
     * Setter for EndTime.
     * The end time of the range of transactions to list.
     * @param endTime Value for String
     */
    @JsonSetter("end_time")
    public void setEndTime(String endTime) {
        this.endTime = endTime;
    }

    /**
     * Converts this ListSubscriptionTransactionsInput into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ListSubscriptionTransactionsInput [" + "id=" + id + ", startTime=" + startTime
                + ", endTime=" + endTime + "]";
    }

    /**
     * Builds a new {@link ListSubscriptionTransactionsInput.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link ListSubscriptionTransactionsInput.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(id, startTime, endTime);
        return builder;
    }

    /**
     * Class to build instances of {@link ListSubscriptionTransactionsInput}.
     */
    public static class Builder {
        private String id;
        private String startTime;
        private String endTime;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  id  String value for id.
         * @param  startTime  String value for startTime.
         * @param  endTime  String value for endTime.
         */
        public Builder(String id, String startTime, String endTime) {
            this.id = id;
            this.startTime = startTime;
            this.endTime = endTime;
        }

        /**
         * Setter for id.
         * @param  id  String value for id.
         * @return Builder
         */
        public Builder id(String id) {
            this.id = id;
            return this;
        }

        /**
         * Setter for startTime.
         * @param  startTime  String value for startTime.
         * @return Builder
         */
        public Builder startTime(String startTime) {
            this.startTime = startTime;
            return this;
        }

        /**
         * Setter for endTime.
         * @param  endTime  String value for endTime.
         * @return Builder
         */
        public Builder endTime(String endTime) {
            this.endTime = endTime;
            return this;
        }

        /**
         * Builds a new {@link ListSubscriptionTransactionsInput} object using the set fields.
         * @return {@link ListSubscriptionTransactionsInput}
         */
        public ListSubscriptionTransactionsInput build() {
            return new ListSubscriptionTransactionsInput(id, startTime, endTime);
        }
    }
}
