/*
 * PaypalServerSdkLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.paypal.sdk.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for NativeAppContext type.
 */
public class NativeAppContext {
    private OsType osType;
    private String osVersion;

    /**
     * Default constructor.
     */
    public NativeAppContext() {
    }

    /**
     * Initialization constructor.
     * @param  osType  OsType value for osType.
     * @param  osVersion  String value for osVersion.
     */
    public NativeAppContext(
            OsType osType,
            String osVersion) {
        this.osType = osType;
        this.osVersion = osVersion;
    }

    /**
     * Getter for OsType.
     * Operating System type of the device that the buyer is using.
     * @return Returns the OsType
     */
    @JsonGetter("os_type")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public OsType getOsType() {
        return osType;
    }

    /**
     * Setter for OsType.
     * Operating System type of the device that the buyer is using.
     * @param osType Value for OsType
     */
    @JsonSetter("os_type")
    public void setOsType(OsType osType) {
        this.osType = osType;
    }

    /**
     * Getter for OsVersion.
     * Operating System version of the device that the buyer is using.
     * @return Returns the String
     */
    @JsonGetter("os_version")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getOsVersion() {
        return osVersion;
    }

    /**
     * Setter for OsVersion.
     * Operating System version of the device that the buyer is using.
     * @param osVersion Value for String
     */
    @JsonSetter("os_version")
    public void setOsVersion(String osVersion) {
        this.osVersion = osVersion;
    }

    /**
     * Converts this NativeAppContext into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "NativeAppContext [" + "osType=" + osType + ", osVersion=" + osVersion + "]";
    }

    /**
     * Builds a new {@link NativeAppContext.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link NativeAppContext.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .osType(getOsType())
                .osVersion(getOsVersion());
        return builder;
    }

    /**
     * Class to build instances of {@link NativeAppContext}.
     */
    public static class Builder {
        private OsType osType;
        private String osVersion;



        /**
         * Setter for osType.
         * @param  osType  OsType value for osType.
         * @return Builder
         */
        public Builder osType(OsType osType) {
            this.osType = osType;
            return this;
        }

        /**
         * Setter for osVersion.
         * @param  osVersion  String value for osVersion.
         * @return Builder
         */
        public Builder osVersion(String osVersion) {
            this.osVersion = osVersion;
            return this;
        }

        /**
         * Builds a new {@link NativeAppContext} object using the set fields.
         * @return {@link NativeAppContext}
         */
        public NativeAppContext build() {
            return new NativeAppContext(osType, osVersion);
        }
    }
}
