/*
 * PaypalServerSdkLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.paypal.sdk.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for SubscriberRequest type.
 */
public class SubscriberRequest {
    private String emailAddress;
    private String payerId;
    private Name name;
    private ShippingDetails shippingAddress;
    private SubscriptionPaymentSource paymentSource;
    private PhoneWithType phone;

    /**
     * Default constructor.
     */
    public SubscriberRequest() {
    }

    /**
     * Initialization constructor.
     * @param  emailAddress  String value for emailAddress.
     * @param  payerId  String value for payerId.
     * @param  name  Name value for name.
     * @param  shippingAddress  ShippingDetails value for shippingAddress.
     * @param  paymentSource  SubscriptionPaymentSource value for paymentSource.
     * @param  phone  PhoneWithType value for phone.
     */
    public SubscriberRequest(
            String emailAddress,
            String payerId,
            Name name,
            ShippingDetails shippingAddress,
            SubscriptionPaymentSource paymentSource,
            PhoneWithType phone) {
        this.emailAddress = emailAddress;
        this.payerId = payerId;
        this.name = name;
        this.shippingAddress = shippingAddress;
        this.paymentSource = paymentSource;
        this.phone = phone;
    }

    /**
     * Getter for EmailAddress.
     * The internationalized email address. Note: Up to 64 characters are allowed before and 255
     * characters are allowed after the {@literal @} sign. However, the generally accepted maximum length for
     * an email address is 254 characters. The pattern verifies that an unquoted {@literal @} sign exists.
     * @return Returns the String
     */
    @JsonGetter("email_address")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getEmailAddress() {
        return emailAddress;
    }

    /**
     * Setter for EmailAddress.
     * The internationalized email address. Note: Up to 64 characters are allowed before and 255
     * characters are allowed after the {@literal @} sign. However, the generally accepted maximum length for
     * an email address is 254 characters. The pattern verifies that an unquoted {@literal @} sign exists.
     * @param emailAddress Value for String
     */
    @JsonSetter("email_address")
    public void setEmailAddress(String emailAddress) {
        this.emailAddress = emailAddress;
    }

    /**
     * Getter for PayerId.
     * The account identifier for a PayPal account.
     * @return Returns the String
     */
    @JsonGetter("payer_id")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getPayerId() {
        return payerId;
    }

    /**
     * Setter for PayerId.
     * The account identifier for a PayPal account.
     * @param payerId Value for String
     */
    @JsonSetter("payer_id")
    public void setPayerId(String payerId) {
        this.payerId = payerId;
    }

    /**
     * Getter for Name.
     * The name of the party.
     * @return Returns the Name
     */
    @JsonGetter("name")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Name getName() {
        return name;
    }

    /**
     * Setter for Name.
     * The name of the party.
     * @param name Value for Name
     */
    @JsonSetter("name")
    public void setName(Name name) {
        this.name = name;
    }

    /**
     * Getter for ShippingAddress.
     * The shipping details.
     * @return Returns the ShippingDetails
     */
    @JsonGetter("shipping_address")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public ShippingDetails getShippingAddress() {
        return shippingAddress;
    }

    /**
     * Setter for ShippingAddress.
     * The shipping details.
     * @param shippingAddress Value for ShippingDetails
     */
    @JsonSetter("shipping_address")
    public void setShippingAddress(ShippingDetails shippingAddress) {
        this.shippingAddress = shippingAddress;
    }

    /**
     * Getter for PaymentSource.
     * The payment source definition. To be eligible to create subscription using debit or credit
     * card, you will need to sign up here (https://www.paypal.com/bizsignup/entry/product/ppcp).
     * Please note, its available only for non-3DS cards and for merchants in US and AU regions.
     * @return Returns the SubscriptionPaymentSource
     */
    @JsonGetter("payment_source")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public SubscriptionPaymentSource getPaymentSource() {
        return paymentSource;
    }

    /**
     * Setter for PaymentSource.
     * The payment source definition. To be eligible to create subscription using debit or credit
     * card, you will need to sign up here (https://www.paypal.com/bizsignup/entry/product/ppcp).
     * Please note, its available only for non-3DS cards and for merchants in US and AU regions.
     * @param paymentSource Value for SubscriptionPaymentSource
     */
    @JsonSetter("payment_source")
    public void setPaymentSource(SubscriptionPaymentSource paymentSource) {
        this.paymentSource = paymentSource;
    }

    /**
     * Getter for Phone.
     * The phone information.
     * @return Returns the PhoneWithType
     */
    @JsonGetter("phone")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public PhoneWithType getPhone() {
        return phone;
    }

    /**
     * Setter for Phone.
     * The phone information.
     * @param phone Value for PhoneWithType
     */
    @JsonSetter("phone")
    public void setPhone(PhoneWithType phone) {
        this.phone = phone;
    }

    /**
     * Converts this SubscriberRequest into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "SubscriberRequest [" + "emailAddress=" + emailAddress + ", payerId=" + payerId
                + ", name=" + name + ", shippingAddress=" + shippingAddress + ", paymentSource="
                + paymentSource + ", phone=" + phone + "]";
    }

    /**
     * Builds a new {@link SubscriberRequest.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link SubscriberRequest.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .emailAddress(getEmailAddress())
                .payerId(getPayerId())
                .name(getName())
                .shippingAddress(getShippingAddress())
                .paymentSource(getPaymentSource())
                .phone(getPhone());
        return builder;
    }

    /**
     * Class to build instances of {@link SubscriberRequest}.
     */
    public static class Builder {
        private String emailAddress;
        private String payerId;
        private Name name;
        private ShippingDetails shippingAddress;
        private SubscriptionPaymentSource paymentSource;
        private PhoneWithType phone;



        /**
         * Setter for emailAddress.
         * @param  emailAddress  String value for emailAddress.
         * @return Builder
         */
        public Builder emailAddress(String emailAddress) {
            this.emailAddress = emailAddress;
            return this;
        }

        /**
         * Setter for payerId.
         * @param  payerId  String value for payerId.
         * @return Builder
         */
        public Builder payerId(String payerId) {
            this.payerId = payerId;
            return this;
        }

        /**
         * Setter for name.
         * @param  name  Name value for name.
         * @return Builder
         */
        public Builder name(Name name) {
            this.name = name;
            return this;
        }

        /**
         * Setter for shippingAddress.
         * @param  shippingAddress  ShippingDetails value for shippingAddress.
         * @return Builder
         */
        public Builder shippingAddress(ShippingDetails shippingAddress) {
            this.shippingAddress = shippingAddress;
            return this;
        }

        /**
         * Setter for paymentSource.
         * @param  paymentSource  SubscriptionPaymentSource value for paymentSource.
         * @return Builder
         */
        public Builder paymentSource(SubscriptionPaymentSource paymentSource) {
            this.paymentSource = paymentSource;
            return this;
        }

        /**
         * Setter for phone.
         * @param  phone  PhoneWithType value for phone.
         * @return Builder
         */
        public Builder phone(PhoneWithType phone) {
            this.phone = phone;
            return this;
        }

        /**
         * Builds a new {@link SubscriberRequest} object using the set fields.
         * @return {@link SubscriberRequest}
         */
        public SubscriberRequest build() {
            return new SubscriberRequest(emailAddress, payerId, name, shippingAddress,
                    paymentSource, phone);
        }
    }
}
