/*
 * PaypalServerSdkLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.paypal.sdk.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for SubscriberRequest type.
 */
public class SubscriberRequest {
    private Name name;
    private PhoneWithType phone;
    private ShippingDetails shippingAddress;
    private SubscriptionPaymentSource paymentSource;

    /**
     * Default constructor.
     */
    public SubscriberRequest() {
    }

    /**
     * Initialization constructor.
     * @param  name  Name value for name.
     * @param  phone  PhoneWithType value for phone.
     * @param  shippingAddress  ShippingDetails value for shippingAddress.
     * @param  paymentSource  SubscriptionPaymentSource value for paymentSource.
     */
    public SubscriberRequest(
            Name name,
            PhoneWithType phone,
            ShippingDetails shippingAddress,
            SubscriptionPaymentSource paymentSource) {
        this.name = name;
        this.phone = phone;
        this.shippingAddress = shippingAddress;
        this.paymentSource = paymentSource;
    }

    /**
     * Getter for Name.
     * The name of the party.
     * @return Returns the Name
     */
    @JsonGetter("name")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Name getName() {
        return name;
    }

    /**
     * Setter for Name.
     * The name of the party.
     * @param name Value for Name
     */
    @JsonSetter("name")
    public void setName(Name name) {
        this.name = name;
    }

    /**
     * Getter for Phone.
     * The phone information.
     * @return Returns the PhoneWithType
     */
    @JsonGetter("phone")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public PhoneWithType getPhone() {
        return phone;
    }

    /**
     * Setter for Phone.
     * The phone information.
     * @param phone Value for PhoneWithType
     */
    @JsonSetter("phone")
    public void setPhone(PhoneWithType phone) {
        this.phone = phone;
    }

    /**
     * Getter for ShippingAddress.
     * The shipping details.
     * @return Returns the ShippingDetails
     */
    @JsonGetter("shipping_address")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public ShippingDetails getShippingAddress() {
        return shippingAddress;
    }

    /**
     * Setter for ShippingAddress.
     * The shipping details.
     * @param shippingAddress Value for ShippingDetails
     */
    @JsonSetter("shipping_address")
    public void setShippingAddress(ShippingDetails shippingAddress) {
        this.shippingAddress = shippingAddress;
    }

    /**
     * Getter for PaymentSource.
     * The payment source definition. To be eligible to create subscription using debit or credit
     * card, you will need to sign up here (https://www.paypal.com/bizsignup/entry/product/ppcp).
     * Please note, its available only for non-3DS cards and for merchants in US and AU regions.
     * @return Returns the SubscriptionPaymentSource
     */
    @JsonGetter("payment_source")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public SubscriptionPaymentSource getPaymentSource() {
        return paymentSource;
    }

    /**
     * Setter for PaymentSource.
     * The payment source definition. To be eligible to create subscription using debit or credit
     * card, you will need to sign up here (https://www.paypal.com/bizsignup/entry/product/ppcp).
     * Please note, its available only for non-3DS cards and for merchants in US and AU regions.
     * @param paymentSource Value for SubscriptionPaymentSource
     */
    @JsonSetter("payment_source")
    public void setPaymentSource(SubscriptionPaymentSource paymentSource) {
        this.paymentSource = paymentSource;
    }

    /**
     * Converts this SubscriberRequest into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "SubscriberRequest [" + "name=" + name + ", phone=" + phone + ", shippingAddress="
                + shippingAddress + ", paymentSource=" + paymentSource + "]";
    }

    /**
     * Builds a new {@link SubscriberRequest.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link SubscriberRequest.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .name(getName())
                .phone(getPhone())
                .shippingAddress(getShippingAddress())
                .paymentSource(getPaymentSource());
        return builder;
    }

    /**
     * Class to build instances of {@link SubscriberRequest}.
     */
    public static class Builder {
        private Name name;
        private PhoneWithType phone;
        private ShippingDetails shippingAddress;
        private SubscriptionPaymentSource paymentSource;



        /**
         * Setter for name.
         * @param  name  Name value for name.
         * @return Builder
         */
        public Builder name(Name name) {
            this.name = name;
            return this;
        }

        /**
         * Setter for phone.
         * @param  phone  PhoneWithType value for phone.
         * @return Builder
         */
        public Builder phone(PhoneWithType phone) {
            this.phone = phone;
            return this;
        }

        /**
         * Setter for shippingAddress.
         * @param  shippingAddress  ShippingDetails value for shippingAddress.
         * @return Builder
         */
        public Builder shippingAddress(ShippingDetails shippingAddress) {
            this.shippingAddress = shippingAddress;
            return this;
        }

        /**
         * Setter for paymentSource.
         * @param  paymentSource  SubscriptionPaymentSource value for paymentSource.
         * @return Builder
         */
        public Builder paymentSource(SubscriptionPaymentSource paymentSource) {
            this.paymentSource = paymentSource;
            return this;
        }

        /**
         * Builds a new {@link SubscriberRequest} object using the set fields.
         * @return {@link SubscriberRequest}
         */
        public SubscriberRequest build() {
            return new SubscriberRequest(name, phone, shippingAddress, paymentSource);
        }
    }
}
