/*
 * PaypalServerSdkLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.paypal.sdk.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for SuspendSubscriptionInput type.
 */
public class SuspendSubscriptionInput {
    private String id;
    private String contentType;
    private SuspendSubscription body;

    /**
     * Default constructor.
     */
    public SuspendSubscriptionInput() {
        contentType = "application/json";
    }

    /**
     * Initialization constructor.
     * @param  id  String value for id.
     * @param  contentType  String value for contentType.
     * @param  body  SuspendSubscription value for body.
     */
    public SuspendSubscriptionInput(
            String id,
            String contentType,
            SuspendSubscription body) {
        this.id = id;
        this.contentType = contentType;
        this.body = body;
    }

    /**
     * Getter for Id.
     * The ID of the subscription.
     * @return Returns the String
     */
    @JsonGetter("id")
    public String getId() {
        return id;
    }

    /**
     * Setter for Id.
     * The ID of the subscription.
     * @param id Value for String
     */
    @JsonSetter("id")
    public void setId(String id) {
        this.id = id;
    }

    /**
     * Getter for ContentType.
     * @return Returns the String
     */
    @JsonGetter("Content-Type")
    public String getContentType() {
        return contentType;
    }

    /**
     * Setter for ContentType.
     * @param contentType Value for String
     */
    @JsonSetter("Content-Type")
    private void setContentType(String contentType) {
        this.contentType = contentType;
    }

    /**
     * Getter for Body.
     * @return Returns the SuspendSubscription
     */
    @JsonGetter("body")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public SuspendSubscription getBody() {
        return body;
    }

    /**
     * Setter for Body.
     * @param body Value for SuspendSubscription
     */
    @JsonSetter("body")
    public void setBody(SuspendSubscription body) {
        this.body = body;
    }

    /**
     * Converts this SuspendSubscriptionInput into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "SuspendSubscriptionInput [" + "id=" + id + ", contentType=" + contentType
                + ", body=" + body + "]";
    }

    /**
     * Builds a new {@link SuspendSubscriptionInput.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link SuspendSubscriptionInput.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(id, contentType)
                .body(getBody());
        return builder;
    }

    /**
     * Class to build instances of {@link SuspendSubscriptionInput}.
     */
    public static class Builder {
        private String id;
        private String contentType = "application/json";
        private SuspendSubscription body;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  id  String value for id.
         * @param  contentType  String value for contentType.
         */
        public Builder(String id, String contentType) {
            this.id = id;
            this.contentType = contentType;
        }

        /**
         * Setter for id.
         * @param  id  String value for id.
         * @return Builder
         */
        public Builder id(String id) {
            this.id = id;
            return this;
        }

        /**
         * Setter for contentType.
         * @param  contentType  String value for contentType.
         * @return Builder
         */
        public Builder contentType(String contentType) {
            this.contentType = contentType;
            return this;
        }

        /**
         * Setter for body.
         * @param  body  SuspendSubscription value for body.
         * @return Builder
         */
        public Builder body(SuspendSubscription body) {
            this.body = body;
            return this;
        }

        /**
         * Builds a new {@link SuspendSubscriptionInput} object using the set fields.
         * @return {@link SuspendSubscriptionInput}
         */
        public SuspendSubscriptionInput build() {
            return new SuspendSubscriptionInput(id, contentType, body);
        }
    }
}
