/*
 * PayPalRESTAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.paypal.api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for BankPaymentToken type.
 */
public class BankPaymentToken {
    private ACHDebitResponse achDebit;
    private SEPADebitResponse sepaDebit;

    /**
     * Default constructor.
     */
    public BankPaymentToken() {
    }

    /**
     * Initialization constructor.
     * @param  achDebit  ACHDebitResponse value for achDebit.
     * @param  sepaDebit  SEPADebitResponse value for sepaDebit.
     */
    public BankPaymentToken(
            ACHDebitResponse achDebit,
            SEPADebitResponse sepaDebit) {
        this.achDebit = achDebit;
        this.sepaDebit = sepaDebit;
    }

    /**
     * Getter for AchDebit.
     * A Resource representing a response of vaulted a ACH Debit Account.
     * @return Returns the ACHDebitResponse
     */
    @JsonGetter("ach_debit")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public ACHDebitResponse getAchDebit() {
        return achDebit;
    }

    /**
     * Setter for AchDebit.
     * A Resource representing a response of vaulted a ACH Debit Account.
     * @param achDebit Value for ACHDebitResponse
     */
    @JsonSetter("ach_debit")
    public void setAchDebit(ACHDebitResponse achDebit) {
        this.achDebit = achDebit;
    }

    /**
     * Getter for SepaDebit.
     * @return Returns the SEPADebitResponse
     */
    @JsonGetter("sepa_debit")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public SEPADebitResponse getSepaDebit() {
        return sepaDebit;
    }

    /**
     * Setter for SepaDebit.
     * @param sepaDebit Value for SEPADebitResponse
     */
    @JsonSetter("sepa_debit")
    public void setSepaDebit(SEPADebitResponse sepaDebit) {
        this.sepaDebit = sepaDebit;
    }

    /**
     * Converts this BankPaymentToken into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "BankPaymentToken [" + "achDebit=" + achDebit + ", sepaDebit=" + sepaDebit + "]";
    }

    /**
     * Builds a new {@link BankPaymentToken.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link BankPaymentToken.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .achDebit(getAchDebit())
                .sepaDebit(getSepaDebit());
        return builder;
    }

    /**
     * Class to build instances of {@link BankPaymentToken}.
     */
    public static class Builder {
        private ACHDebitResponse achDebit;
        private SEPADebitResponse sepaDebit;



        /**
         * Setter for achDebit.
         * @param  achDebit  ACHDebitResponse value for achDebit.
         * @return Builder
         */
        public Builder achDebit(ACHDebitResponse achDebit) {
            this.achDebit = achDebit;
            return this;
        }

        /**
         * Setter for sepaDebit.
         * @param  sepaDebit  SEPADebitResponse value for sepaDebit.
         * @return Builder
         */
        public Builder sepaDebit(SEPADebitResponse sepaDebit) {
            this.sepaDebit = sepaDebit;
            return this;
        }

        /**
         * Builds a new {@link BankPaymentToken} object using the set fields.
         * @return {@link BankPaymentToken}
         */
        public BankPaymentToken build() {
            return new BankPaymentToken(achDebit, sepaDebit);
        }
    }
}
