/*
 * PayPalRESTAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.paypal.api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for OrdersConfirmInput type.
 */
public class OrdersConfirmInput {
    private String id;
    private String contentType;
    private String payPalClientMetadataId;
    private String prefer;
    private ConfirmOrderRequest body;

    /**
     * Default constructor.
     */
    public OrdersConfirmInput() {
        contentType = "application/json";
        prefer = "return=minimal";
    }

    /**
     * Initialization constructor.
     * @param  id  String value for id.
     * @param  contentType  String value for contentType.
     * @param  payPalClientMetadataId  String value for payPalClientMetadataId.
     * @param  prefer  String value for prefer.
     * @param  body  ConfirmOrderRequest value for body.
     */
    public OrdersConfirmInput(
            String id,
            String contentType,
            String payPalClientMetadataId,
            String prefer,
            ConfirmOrderRequest body) {
        this.id = id;
        this.contentType = contentType;
        this.payPalClientMetadataId = payPalClientMetadataId;
        this.prefer = prefer;
        this.body = body;
    }

    /**
     * Getter for Id.
     * The ID of the order for which the payer confirms their intent to pay.
     * @return Returns the String
     */
    @JsonGetter("id")
    public String getId() {
        return id;
    }

    /**
     * Setter for Id.
     * The ID of the order for which the payer confirms their intent to pay.
     * @param id Value for String
     */
    @JsonSetter("id")
    public void setId(String id) {
        this.id = id;
    }

    /**
     * Getter for ContentType.
     * @return Returns the String
     */
    @JsonGetter("Content-Type")
    public String getContentType() {
        return contentType;
    }

    /**
     * Setter for ContentType.
     * @param contentType Value for String
     */
    @JsonSetter("Content-Type")
    private void setContentType(String contentType) {
        this.contentType = contentType;
    }

    /**
     * Getter for PayPalClientMetadataId.
     * @return Returns the String
     */
    @JsonGetter("PayPal-Client-Metadata-Id")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getPayPalClientMetadataId() {
        return payPalClientMetadataId;
    }

    /**
     * Setter for PayPalClientMetadataId.
     * @param payPalClientMetadataId Value for String
     */
    @JsonSetter("PayPal-Client-Metadata-Id")
    public void setPayPalClientMetadataId(String payPalClientMetadataId) {
        this.payPalClientMetadataId = payPalClientMetadataId;
    }

    /**
     * Getter for Prefer.
     * The preferred server response upon successful completion of the request. Value
     * is:&lt;ul&gt;&lt;li&gt;&lt;code&gt;return=minimal&lt;/code&gt;. The server returns a minimal response to optimize
     * communication between the API caller and the server. A minimal response includes the
     * &lt;code&gt;id&lt;/code&gt;, &lt;code&gt;status&lt;/code&gt; and HATEOAS
     * links.&lt;/li&gt;&lt;li&gt;&lt;code&gt;return=representation&lt;/code&gt;. The server returns a complete resource
     * representation, including the current state of the resource.&lt;/li&gt;&lt;/ul&gt;
     * @return Returns the String
     */
    @JsonGetter("Prefer")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getPrefer() {
        return prefer;
    }

    /**
     * Setter for Prefer.
     * The preferred server response upon successful completion of the request. Value
     * is:&lt;ul&gt;&lt;li&gt;&lt;code&gt;return=minimal&lt;/code&gt;. The server returns a minimal response to optimize
     * communication between the API caller and the server. A minimal response includes the
     * &lt;code&gt;id&lt;/code&gt;, &lt;code&gt;status&lt;/code&gt; and HATEOAS
     * links.&lt;/li&gt;&lt;li&gt;&lt;code&gt;return=representation&lt;/code&gt;. The server returns a complete resource
     * representation, including the current state of the resource.&lt;/li&gt;&lt;/ul&gt;
     * @param prefer Value for String
     */
    @JsonSetter("Prefer")
    public void setPrefer(String prefer) {
        this.prefer = prefer;
    }

    /**
     * Getter for Body.
     * @return Returns the ConfirmOrderRequest
     */
    @JsonGetter("body")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public ConfirmOrderRequest getBody() {
        return body;
    }

    /**
     * Setter for Body.
     * @param body Value for ConfirmOrderRequest
     */
    @JsonSetter("body")
    public void setBody(ConfirmOrderRequest body) {
        this.body = body;
    }

    /**
     * Converts this OrdersConfirmInput into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "OrdersConfirmInput [" + "id=" + id + ", contentType=" + contentType
                + ", payPalClientMetadataId=" + payPalClientMetadataId + ", prefer=" + prefer
                + ", body=" + body + "]";
    }

    /**
     * Builds a new {@link OrdersConfirmInput.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link OrdersConfirmInput.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(id, contentType)
                .payPalClientMetadataId(getPayPalClientMetadataId())
                .prefer(getPrefer())
                .body(getBody());
        return builder;
    }

    /**
     * Class to build instances of {@link OrdersConfirmInput}.
     */
    public static class Builder {
        private String id;
        private String contentType = "application/json";
        private String payPalClientMetadataId;
        private String prefer = "return=minimal";
        private ConfirmOrderRequest body;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  id  String value for id.
         * @param  contentType  String value for contentType.
         */
        public Builder(String id, String contentType) {
            this.id = id;
            this.contentType = contentType;
        }

        /**
         * Setter for id.
         * @param  id  String value for id.
         * @return Builder
         */
        public Builder id(String id) {
            this.id = id;
            return this;
        }

        /**
         * Setter for contentType.
         * @param  contentType  String value for contentType.
         * @return Builder
         */
        public Builder contentType(String contentType) {
            this.contentType = contentType;
            return this;
        }

        /**
         * Setter for payPalClientMetadataId.
         * @param  payPalClientMetadataId  String value for payPalClientMetadataId.
         * @return Builder
         */
        public Builder payPalClientMetadataId(String payPalClientMetadataId) {
            this.payPalClientMetadataId = payPalClientMetadataId;
            return this;
        }

        /**
         * Setter for prefer.
         * @param  prefer  String value for prefer.
         * @return Builder
         */
        public Builder prefer(String prefer) {
            this.prefer = prefer;
            return this;
        }

        /**
         * Setter for body.
         * @param  body  ConfirmOrderRequest value for body.
         * @return Builder
         */
        public Builder body(ConfirmOrderRequest body) {
            this.body = body;
            return this;
        }

        /**
         * Builds a new {@link OrdersConfirmInput} object using the set fields.
         * @return {@link OrdersConfirmInput}
         */
        public OrdersConfirmInput build() {
            return new OrdersConfirmInput(id, contentType, payPalClientMetadataId, prefer, body);
        }
    }
}
